[tool.poetry]
name = "quizfetcher"
version = "0.1.0"
description = ""
authors = ["Michael Wiradharma <michael.wiradharma@berkeley.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
